/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as LearningQueueRouteImport } from './routes/learning-queue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningQueueRoute = LearningQueueRouteImport.update({
  id: '/learning-queue',
  path: '/learning-queue',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/session/$id': typeof SessionIdRoute
  '/learning-queue': typeof LearningQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/session/$id': typeof SessionIdRoute
  '/learning-queue': typeof LearningQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/session/$id': typeof SessionIdRoute
  '/learning-queue': typeof LearningQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/session/$id' | '/learning-queue'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/session/$id' | '/learning-queue'
  id: '__root__' | '/' | '/session/$id' | '/learning-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionIdRoute: typeof SessionIdRoute
  LearningQueueRoute: typeof LearningQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-queue': {
      id: '/learning-queue'
      path: '/learning-queue'
      fullPath: '/learning-queue'
      preLoaderRoute: typeof LearningQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionIdRoute: SessionIdRoute,
  LearningQueueRoute: LearningQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
